### ISSUE TITLE
ECONFLICT Unable to find suitable version for veams-js

### ISSUE THREAD

**Issue by ghost** [Sebastian-Fitzner/veams-js#16]
Node.js Terminal Input: veams -i vjs

package.json exists in the directory where the command is executed.
OS: WIN10 

> Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "bower install veams-js "
> bower                        ECONFLICT Unable to find suitable version for veams-js

Solution: "bower install veams-js" in the project directory

**Comment by Sebastian-Fitzner** [comment]
Looks like bower had a problem to find the package. I have tested it, but it looks like it is not a veams-js or veams specifc problem so I will close the ticket ...
